// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivejotjayztnywiunbxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2ZWpvdGpheXp0bnl3aXVuYnhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNzIxMzksImV4cCI6MjA1ODY0ODEzOX0.TPpA-Rb-JyBeubbY3ZIK-8Y-nvXfNAZoif3EG_O-QS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);